import math
from tkinter import *
print("Введите уравнение вида ax²+bx+c=0")
a=int(input("Введите a>>"))
b=int(input("Введите b>>"))
c=int(input("Введите c>>"))
print("   ")
print("^^Введенные вами данные^^")
print("█████████████████████████")
print("↓↓Ответ       программы↓↓")
D=b*b - 4 * a * c
print("a=",a,"  ██ D=(",b,")²- 4*",a,"*",c,"=",D)
if D>0:
     print("b=",b,"  ██ x1,2= -b ± √D     -(",b,")±√",D)
     print("c=",c," ██       ------- = ----------------")
     print("                  2*a         2*",a         )
     x1=(-b+math.sqrt(D))/(2*a)
     x2=(-b-math.sqrt(D))/(2*a)
     print("   ")
     print("Ответ программы:")
     print("x1=",x1,)
     print("x2=",x2,)

if D<0:
     print("b=",b,"  ██  Дискриминант(",D,") < 0")
     print("c=",c,"  ██   Корней не существует!")
     print("   ")
     print("Ответ программы:")
     print("Корней не существует!")
if D==0:
     print("b=",b,"  ██ x1,2= -b ± √D     -(",b,")±√",D)
     print("c=",c," ██       ------- = ----------------")
     print("                  2*a         2*",a         )
     x=(-b+math.sqrt(D))/(2*a)
     print("   ")
     print("Ответ программы:")
     print("x=",x)
print("   ")
print("   ")
print("   ")
print("Код был написан группой людей на бесплатной основе...")
print("Мы не будем против, если вы поддержите нас денюжкой.")
print(" ")
print("Мы в ВК: https://vk.com/serving_antifem")
